const SCHEMA_VERSION=1;
const DATA_KEY='futureCompassDataV1';
const LEGACY_PROGRESS_KEY='futureCompassV042Repo';
const T='futureCompassTheme';
const A='futureCompassAdult';
let week=0;
let sel={fun:'',difficulty:'',again:''};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function now(){return new Date().toISOString()}
function makeId(prefix='profile'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
function makeProfile(name='Explorer'){const t=now();return{id:makeId(),displayName:name.trim()||'Explorer',ageBand:'10-12',theme:localStorage.getItem(T)||'bright',progress:{},badgeEvidence:[],createdAt:t,updatedAt:t}}
function defaultData(){const p=makeProfile('Explorer');return{app:'Future Compass',schemaVersion:SCHEMA_VERSION,activeProfileId:p.id,profiles:[p],createdAt:now(),updatedAt:now()}}
function normalizeData(d){if(!d||typeof d!=='object')return null;if(d.schemaVersion!==SCHEMA_VERSION||!Array.isArray(d.profiles))return null;d.profiles=d.profiles.map(p=>({id:p.id||makeId(),displayName:p.displayName||'Explorer',ageBand:p.ageBand||'10-12',theme:p.theme||'bright',progress:p.progress&&typeof p.progress==='object'?p.progress:{},badgeEvidence:Array.isArray(p.badgeEvidence)?p.badgeEvidence:[],createdAt:p.createdAt||now(),updatedAt:p.updatedAt||now()}));if(!d.profiles.length)d.profiles=[makeProfile('Explorer')];if(!d.profiles.some(p=>p.id===d.activeProfileId))d.activeProfileId=d.profiles[0].id;d.app='Future Compass';d.schemaVersion=SCHEMA_VERSION;d.updatedAt=d.updatedAt||now();d.createdAt=d.createdAt||now();return d}
function migrateLegacy(){try{const legacy=JSON.parse(localStorage.getItem(LEGACY_PROGRESS_KEY));if(legacy&&typeof legacy==='object'&&!Array.isArray(legacy)){const d=defaultData();activeProfile(d).progress=legacy;d.updatedAt=now();return d}}catch{}return defaultData()}
function loadData(){try{const parsed=JSON.parse(localStorage.getItem(DATA_KEY));const normalized=normalizeData(parsed);if(normalized)return normalized}catch{}const migrated=migrateLegacy();saveData(migrated);return migrated}
function saveData(d){d.updatedAt=now();localStorage.setItem(DATA_KEY,JSON.stringify(d))}
function data(){return loadData()}
function activeProfile(d=data()){return d.profiles.find(p=>p.id===d.activeProfileId)||d.profiles[0]}
function prog(){return activeProfile().progress||{}}
function currentActivity(){return activities[week]}
function moduleMode(){try{return activeModuleMode||'showMe'}catch{return 'showMe'}}
function renderProfiles(){const d=data(),select=$('profileSelect');if(!select)return;select.innerHTML=d.profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.displayName)}</option>`).join('');select.value=d.activeProfileId;const profile=activeProfile(d);$('profileSummary').textContent=`Current profile: ${profile.displayName} · schema v${d.schemaVersion}`}
function addProfile(){const name=prompt('Profile nickname?','Explorer');if(name===null)return;const d=data();const p=makeProfile(name);d.profiles.push(p);d.activeProfileId=p.id;saveData(d);render();showView('today')}
function switchProfile(id){const d=data();if(!d.profiles.some(p=>p.id===id))return;d.activeProfileId=id;saveData(d);render()}
function validateImport(obj){if(obj&&obj.schemaVersion===SCHEMA_VERSION&&Array.isArray(obj.profiles))return normalizeData(obj);if(obj&&obj.progress&&typeof obj.progress==='object'){const d=defaultData();activeProfile(d).progress=obj.progress;return d}if(obj&&typeof obj==='object'&&!Array.isArray(obj)){const d=defaultData();activeProfile(d).progress=obj;return d}return null}
function exportBackup(){const d=data();const blob=new Blob([JSON.stringify({...d,exportedAt:now()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='future-compass-backup.json';a.click();URL.revokeObjectURL(url)}
function importBackup(file){const reader=new FileReader();reader.onload=()=>{try{const imported=validateImport(JSON.parse(reader.result));if(!imported){alert('Import failed: file did not match a supported Future Compass backup format.');return}if(!confirm('Import this backup and replace local Future Compass data on this device?'))return;saveData(imported);render();showView('today');alert('Import complete.')}catch(err){alert(`Import failed: ${err.message}`)}};reader.readAsText(file)}
function evidenceForEntry(activity,entry,weekIndex){const weight=(entry.fun==='Fun'||entry.again==='Yes')?2:1;return activity.badges.map(b=>({badge:b,activityId:activity.id,weekIndex,source:'activity-reflection',weight,note:entry.favoritePart||'',createdAt:entry.savedAt}))}
function level(n){if(!n)return{name:'Locked',icon:'🔒',steps:0};if(n<=1)return{name:'Starter',icon:'🌱',steps:1};if(n<=3)return{name:'Explorer',icon:'🧭',steps:2};if(n<=5)return{name:'Builder',icon:'🏗️',steps:3};return{name:'Guide',icon:'🌟',steps:4}}
function badgeSummary(p=activeProfile()){const counts={};(p.badgeEvidence||[]).forEach(e=>counts[e.badge]=(counts[e.badge]||0)+(Number(e.weight)||1));if(!Object.keys(counts).length){Object.entries(p.progress||{}).forEach(([i,e])=>{const a=activities[+i];if(!a)return;const liked=e.fun==='Fun'||e.again==='Yes';if(!(e.fun||e.difficulty||e.again||e.favoritePart))return;a.badges.forEach(b=>counts[b]=(counts[b]||0)+(liked?2:1))})}return Object.keys(paths).map(b=>({badge:b,score:counts[b]||0,level:level(counts[b]||0),path:paths[b]})).sort((a,b)=>b.score-a.score||a.badge.localeCompare(b.badge))}
function summary(){const p=activeProfile(),entries=Object.entries(p.progress||{}).sort((a,b)=>+a[0]-+b[0]),badges=badgeSummary(p),top=badges.filter(b=>b.score>0).slice(0,5),signals={};entries.forEach(([i,e])=>{const a=activities[+i];if(!a)return;const w=(e.fun==='Fun'||e.again==='Yes')?2:((e.fun==='Okay'||e.again==='Maybe')?1:0);a.adult.forEach(s=>signals[s]=(signals[s]||0)+w)});return{profile:p,saved:entries.length,fun:entries.filter(([,e])=>e.fun==='Fun').length,yes:entries.filter(([,e])=>e.again==='Yes').length,top,signals:Object.entries(signals).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,6),liked:entries.filter(([,e])=>e.fun==='Fun'||e.again==='Yes').map(([i])=>activities[+i].title).slice(0,6),next:top.map(b=>`${b.path.emoji} ${b.badge}: ${b.path.steps[Math.min(b.level.steps,b.path.steps.length-1)]}`),history:entries.map(([i,e])=>({week:+i+1,title:activities[+i].title,fun:e.fun||'—',difficulty:e.difficulty||'—',again:e.again||'—',favorite:e.favoritePart||'',module:e.moduleEntryUsed||'—'}))}}
function showView(view){if(view==='adult'&&sessionStorage.getItem(A)!=='true'){openGate();return}if(view==='report')renderReport();document.querySelectorAll('.view').forEach(section=>section.classList.toggle('active',section.id===view));document.querySelectorAll('[data-view]').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function render(){renderProfiles();const a=currentActivity(),p=prog(),saved=p[week]||{};sel={fun:saved.fun||'',difficulty:saved.difficulty||'',again:saved.again||''};$('week').textContent=`Week ${week+1} of ${activities.length}`;$('title').textContent=a.title;$('emoji').textContent=a.emoji;$('meta').innerHTML=`<span class="pill">${a.theme}</span><span class="pill">⏱ ${a.time}</span><span class="pill">🧰 ${a.materials}</span>`;$('text').textContent=a.text;$('steps').innerHTML=a.steps.map((x,i)=>`<li><span class="num">${i+1}</span><span>${esc(x)}</span></li>`).join('');$('favorite').value=saved.favoritePart||'';$('saved').style.display='none';document.querySelectorAll('.question').forEach(q=>q.querySelectorAll('.choice').forEach(b=>b.classList.toggle('selected',b.dataset.v===sel[q.dataset.q])));renderAll()}
function renderAll(){const p=activeProfile(),progress=p.progress||{},s=summary();$('fill').style.width=`${Math.round(Object.keys(progress).length/activities.length*100)}%`;$('progress').textContent=`${Object.keys(progress).length} of ${activities.length} activities saved`;const top=badgeSummary(p).filter(b=>b.score>0).slice(0,4);$('miniBadges').innerHTML=top.length?top.map(b=>`<div class="mini"><strong>${b.path.emoji} ${b.badge}</strong><span class="small">${b.path.desc}</span><br><span class="level">${b.level.icon} ${b.level.name}</span></div>`).join(''):`<div class="mini"><strong>No badges yet</strong><span class="small">Save an activity to start earning evidence.</span></div>`;$('badgeGrid').innerHTML=badgeSummary(p).map(b=>{const steps=b.path.steps.map((st,i)=>`<li><span class="${i<b.level.steps?'done':'todo'}">${i<b.level.steps?'✅':'○'}</span><span>${esc(st)}</span></li>`).join('');return`<article class="path"><div class="pathHead"><div><h3>${b.path.emoji} ${b.badge}</h3><p class="small">${b.path.desc}</p></div><div class="pathEmoji">${b.level.icon}</div></div><span class="level">${b.level.name} · Evidence ${b.score}</span><ul class="pathList">${steps}</ul><div class="next">Next challenge: ${esc(b.path.steps[Math.min(b.level.steps,b.path.steps.length-1)])}</div></article>`}).join('');$('adultStats').innerHTML=`<div class="stat"><b>${s.saved}</b><span>activities saved</span></div><div class="stat"><b>${s.fun}</b><span>rated fun</span></div><div class="stat"><b>${s.yes}</b><span>would try again</span></div>`;$('patterns').innerHTML=s.signals.length?s.signals.map(([x,v])=>`<div class="history"><strong>${x.replace(/\b\w/g,m=>m.toUpperCase())}</strong><div class="small">Pattern strength: ${v}</div></div>`).join(''):`<div class="history">No strong patterns yet.</div>`;$('history').innerHTML=s.history.length?s.history.map(h=>`<div class="history"><strong>Week ${h.week}: ${esc(h.title)}</strong><div class="small">Fun: ${esc(h.fun)} · Difficulty: ${esc(h.difficulty)} · Again: ${esc(h.again)} · Start: ${esc(h.module)}</div>${h.favorite?`<p>${esc(h.favorite)}</p>`:''}</div>`).join(''):`<div class="history">No saved activities yet.</div>`;renderReport()}
function renderReport(){const s=summary();$('reportGen').textContent=`Generated ${new Date().toLocaleString()} · ${s.profile.displayName}`;$('reportSaved').textContent=`${s.saved}/${activities.length}`;$('reportStats').innerHTML=`<div class="stat"><b>${s.saved}</b><span>activities saved</span></div><div class="stat"><b>${s.fun}</b><span>rated fun</span></div><div class="stat"><b>${s.yes}</b><span>would try again</span></div>`;const fill=(id,arr,fn,empty)=>$(id).innerHTML=arr.length?arr.map(fn).join(''):`<li>${empty}</li>`;fill('reportBadges',s.top,b=>`<li><strong>${b.path.emoji} ${b.badge}</strong> — ${b.level.name} (${b.score})</li>`,'No badges yet.');fill('reportPatterns',s.signals,([x,v])=>`<li><strong>${esc(x)}</strong> — ${v}</li>`,'No patterns yet.');fill('reportNext',s.next,x=>`<li>${esc(x)}</li>`,'Complete more activities to generate next challenges.');fill('reportLiked',s.liked,x=>`<li>${esc(x)}</li>`,'No liked activities yet.');$('reportHistory').innerHTML=s.history.length?s.history.slice(-6).map(h=>`<div class="history"><strong>Week ${h.week}: ${esc(h.title)}</strong><div class="small">Fun: ${esc(h.fun)} · Difficulty: ${esc(h.difficulty)} · Again: ${esc(h.again)} · Start: ${esc(h.module)}</div>${h.favorite?`<p>${esc(h.favorite)}</p>`:''}</div>`).join(''):`<div class="history">No saved activities yet.</div>`}
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const q=b.closest('.question').dataset.q;sel[q]=b.dataset.v;b.closest('.choices').querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
$('save').onclick=()=>{const d=data(),profile=activeProfile(d),progress=profile.progress||{},a=currentActivity(),entry={activityId:a.id,weekIndex:week,...sel,favoritePart:$('favorite').value.trim(),moduleEntryUsed:moduleMode(),savedAt:now()};progress[week]=entry;profile.progress=progress;profile.badgeEvidence=(profile.badgeEvidence||[]).filter(e=>e.weekIndex!==week);profile.badgeEvidence.push(...evidenceForEntry(a,entry,week));profile.updatedAt=now();saveData(d);$('saved').style.display='block';renderAll()};
$('prev').onclick=()=>{week=Math.max(0,week-1);render()};$('next').onclick=()=>{week=Math.min(activities.length-1,week+1);render()};$('badgeBtn').onclick=()=>showView('badges');$('reportBtn').onclick=()=>showView('report');$('jsonBtn').onclick=$('exportBtn').onclick=exportBackup;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{const file=e.target.files?.[0];if(file)importBackup(file);e.target.value=''};
$('resetBtn').onclick=()=>{if(confirm('Reset progress for the current profile only?')){const d=data(),p=activeProfile(d);p.progress={};p.badgeEvidence=[];p.updatedAt=now();saveData(d);render();lock();showView('today')}};$('theme').onchange=e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem(T,e.target.value);const d=data(),p=activeProfile(d);p.theme=e.target.value;saveData(d)};$('profileSelect').onchange=e=>switchProfile(e.target.value);$('addProfileBtn').onclick=addProfile;
function openGate(){$('err').hidden=true;$('modal').hidden=false;$('pass').value='';setTimeout(()=>$('pass').focus(),50)}function showAdult(){$('adult').hidden=false;$('lock').textContent='🔓 Adult view unlocked';$('adultBtn').textContent='Grown-up View Open';showView('adult')}function lock(){sessionStorage.setItem(A,'false');$('adult').hidden=true;$('lock').textContent='🔒 Adult view locked';$('adultBtn').textContent='🔐 Grown-up Login'}$('adultBtn').onclick=$('mobAdult').onclick=()=>{if(sessionStorage.getItem(A)==='true')showAdult();else openGate()};$('login').onclick=()=>{if($('user').value.trim()!=='grownup'||$('pass').value!=='compass'){$('err').hidden=false;return}sessionStorage.setItem(A,'true');$('modal').hidden=true;showAdult()};$('cancel').onclick=()=>$('modal').hidden=true;$('lockBtn').onclick=()=>{lock();showView('today')};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));const th=localStorage.getItem(T)||activeProfile().theme||'bright';document.documentElement.dataset.theme=th;$('theme').value=th;render();showView('today');
